# Generated by Django 5.2.5 on 2025-09-03 06:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_rating_remove_product_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 3, 6, 9, 53, 702622, tzinfo=datetime.timezone.utc), null=True, verbose_name='Новинка до'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
