# Generated by Django 5.2.5 on 2025-08-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephine', models.TextField(blank=True, max_length=11, null=True, unique=True)),
                ('city', models.TextField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Мужской', 'Male'), ('Женский', 'Female'), ('Другой', 'Other')], default='Другой', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
