# Generated by Django 5.2.5 on 2025-09-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_gender_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telephine',
            new_name='telephone',
        ),
    ]
